# Generated by Django 4.2.2 on 2023-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(blank=True, choices=[('1', 'Facebook'), ('2', 'Twitter'), ('3', 'Instagram'), ('4', 'Linked In')], max_length=2, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Plugin',
                'verbose_name_plural': 'Social Plugin',
            },
        ),
    ]
