# Generated by Django 4.2.2 on 2023-06-19 12:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Draft')], max_length=2, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project-Owner',
                'verbose_name_plural': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='Projectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('short_description', tinymce.models.HTMLField()),
                ('description', tinymce.models.HTMLField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Draft')], max_length=2, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectowner')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
